### ISSUE TITLE
only one virtual node-red device pairable with alexa echo dot

### ISSUE THREAD

**Issue by schoko123** [FezVrasta/node-red-matter#13]
You can pair one virtual device with alexa when you set port udp 5540 - all works correct.
A second virtual device makes weired problems on alexa app and in node-red.
I was not able to setup more than one virtual matter node-red device and control it over alexa.
Any ideas ?

**Comment by Apollon77** [comment]
Yes, this is reasoned by Amazon ... they seem to only look for port 5540. This means: use a bridge OR different Hosts/IPs

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/node-red-matter/wiki/Documentation#i-cant-pair-multiple-devices-to-alexa
