### ISSUE TITLE
Example not working properly

### ISSUE THREAD

**Issue by willi-d** [FezVrasta/node-red-matter#15]
I think that the provided example has an error.
The payload you actually have to send to the matter device control node (at least for a light) has to look like:
```
{ on: true|false }
```

So I guess there is a mapping needed after (or in) the on/off inject nodes.
Also some documentation about the API of the nodes/devices would be great.

 I tried the module in the last days to use it together with knx-ultimate and found that by try/error.

**Comment by iam4k33m** [comment]
Can confirm this is correct: Couldn't control device until I sent {"on": true} or {"on": false} rather than the true or false payload demonstrated.

**Comment by FezVrasta** [comment]
If someone would be so kind to send a PR to correct the documentation I would be extremely grateful. Thanks!
